import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const readCsv = (file) => {
  const [header, ...rows] = fs.readFileSync(path.join(root, "data", file), "utf8").trim().split("\n");
  const columns = header.split(",");
  return rows.map((row, index) => ({ row: index + 2, value: Object.fromEntries(columns.map((column, i) => [column, row.split(",")[i]])) }));
};
const issues = [];
const users = readCsv("users.csv");
const userIds = new Set();
for (const { row, value } of users) {
  if (!value.user_id || !value.signup_date || !value.retained_d30) issues.push(`users.csv row ${row}: required value is missing`);
  if (userIds.has(value.user_id)) issues.push(`users.csv row ${row}: duplicate user_id ${value.user_id}`);
  userIds.add(value.user_id);
  if (Number.isNaN(Date.parse(value.signup_date))) issues.push(`users.csv row ${row}: invalid signup_date`);
}
for (const file of ["workout_logs.csv", "streak_history.csv", "subscriptions.csv"]) {
  const rows = readCsv(file);
  const seen = new Set();
  for (const { row, value } of rows) {
    if (!userIds.has(value.user_id)) issues.push(`${file} row ${row}: unknown user_id ${value.user_id}`);
    const key = file === "workout_logs.csv" ? value.workout_id : value.user_id;
    if (seen.has(key)) issues.push(`${file} row ${row}: duplicate key ${key}`);
    seen.add(key);
    if (file === "workout_logs.csv" && (!Number.isFinite(Number(value.duration_minutes)) || Number(value.duration_minutes) <= 0)) issues.push(`${file} row ${row}: invalid duration_minutes`);
    if (file === "workout_logs.csv" && Number.isNaN(Date.parse(value.completed_at))) issues.push(`${file} row ${row}: invalid completed_at`);
  }
}
const report = [
  "# Data-quality report", "", "Generated by `npm run check:data`.", "",
  `- Users checked: ${users.length}`,
  `- Workout attempts checked: ${readCsv("workout_logs.csv").length}`,
  `- Streak snapshots checked: ${readCsv("streak_history.csv").length}`,
  `- Subscription records checked: ${readCsv("subscriptions.csv").length}`,
  `- Validation issues: ${issues.length}`,
  "", "## Result", "", ...(issues.length ? issues.map((issue) => `- ${issue}`) : ["All structural, key, foreign-key, timestamp, and duration checks passed."]), "",
].join("\n");
const destination = path.join(root, "reports", "data-quality-report.md");
fs.mkdirSync(path.dirname(destination), { recursive: true });
fs.writeFileSync(destination, report);
console.log(issues.length ? `Data-quality checks found ${issues.length} issue(s).` : "Data-quality checks passed.");
if (issues.length) process.exitCode = 1;
