import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const readCsv = (file) => {
  const [header, ...rows] = fs.readFileSync(path.join(root, "data", file), "utf8").trim().split("\n");
  const columns = header.split(",");
  return rows.map((row) => Object.fromEntries(columns.map((column, i) => [column, row.split(",")[i]])));
};
const writeCsv = (file, header, rows) => fs.writeFileSync(path.join(root, "reports", file), [header.join(","), ...rows.map((row) => row.join(","))].join("\n") + "\n");
const features = readCsv("derived/user_features.csv");
const users = new Map(readCsv("users.csv").map((user) => [user.user_id, user]));
const rate = (records) => records.length ? (records.reduce((sum, record) => sum + Number(record.retained_d30), 0) / records.length) : 0;
const percentage = (value) => `${(value * 100).toFixed(1)}%`;

const cohorts = new Map();
for (const feature of features) {
  const month = users.get(feature.user_id).signup_date.slice(0, 7);
  cohorts.set(month, [...(cohorts.get(month) || []), feature]);
}
const cohortRows = [...cohorts.entries()].sort().map(([month, records]) => [month, records.length, percentage(rate(records))]);
writeCsv("cohort-retention.csv", ["signup_month", "users", "d30_retention_rate"], cohortRows);

const definitions = [
  ["Current streak ≥ 7 days", (row) => Number(row.current_streak_days) >= 7],
  ["Completed 3+ workouts", (row) => Number(row.completed_workouts_30d) >= 3],
  ["Completion rate ≥ 80%", (row) => Number(row.completion_rate) >= 0.8],
  ["Annual plan", (row) => Number(row.is_annual_plan) === 1],
  ["Used discount", (row) => Number(row.used_discount) === 1],
];
const baseline = rate(features);
const driverRows = definitions.map(([name, rule]) => {
  const matched = features.filter(rule);
  const matchedRate = rate(matched);
  return [name, matched.length, percentage(matchedRate), `${((matchedRate - baseline) * 100).toFixed(1)}pp`];
});
writeCsv("behaviour-lift.csv", ["segment", "users", "d30_retention_rate", "lift_vs_all_users"], driverRows);

const ranked = [...driverRows].sort((a, b) => Number.parseFloat(b[3]) - Number.parseFloat(a[3]));
const report = [
  "# Exploratory retention analysis", "", "Generated by `npm run analyze:explore` from synthetic prototype data.", "",
  `Overall synthetic D30 retention: **${percentage(baseline)}** (${features.filter((row) => Number(row.retained_d30)).length}/${features.length} users).`,
  "", "## Cohort retention", "", "| Signup month | Users | D30 retention |", "| --- | ---: | ---: |",
  ...cohortRows.map((row) => `| ${row[0]} | ${row[1]} | ${row[2]} |`),
  "", "## Behaviour lift", "", "| Segment | Users | D30 retention | Lift vs all users |", "| --- | ---: | ---: | ---: |",
  ...ranked.map((row) => `| ${row[0]} | ${row[1]} | ${row[2]} | ${row[3]} |`),
  "", "## Interpretation", "", "The apparent ranking is descriptive only: the sample has 12 fictional users and was designed for application development. It cannot establish causality, statistical significance, or real retention drivers.", "",
].join("\n");
fs.writeFileSync(path.join(root, "reports", "exploratory-analysis.md"), report);
console.log(`Generated cohort and behaviour-lift reports for ${features.length} users.`);
