import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const readCsv = (file) => {
  const [header, ...rows] = fs.readFileSync(path.join(root, "data", file), "utf8").trim().split("\n");
  const columns = header.split(",");
  return rows.map((row) => Object.fromEntries(columns.map((column, index) => [column, row.split(",")[index]])));
};
const sigmoid = (value) => 1 / (1 + Math.exp(-Math.max(-30, Math.min(30, value))));
const featureNames = ["completed_workouts_30d", "completion_rate", "days_since_last_workout", "current_streak_days", "is_annual_plan", "used_discount"];
const rows = readCsv("derived/user_features.csv").map((row) => ({
  id: row.user_id,
  y: Number(row.retained_d30),
  x: featureNames.map((name) => Number(row[name])),
}));
const train = rows.filter((_, index) => index < 8);
const test = rows.filter((_, index) => index >= 8);
const means = featureNames.map((_, column) => train.reduce((sum, row) => sum + row.x[column], 0) / train.length);
const stds = featureNames.map((_, column) => {
  const variance = train.reduce((sum, row) => sum + (row.x[column] - means[column]) ** 2, 0) / train.length;
  return Math.sqrt(variance) || 1;
});
const normalise = (row) => [1, ...row.x.map((value, index) => (value - means[index]) / stds[index])];
let weights = Array(featureNames.length + 1).fill(0);
for (let iteration = 0; iteration < 2500; iteration += 1) {
  const gradient = Array(weights.length).fill(0);
  for (const row of train) {
    const x = normalise(row);
    const error = sigmoid(x.reduce((sum, value, index) => sum + value * weights[index], 0)) - row.y;
    x.forEach((value, index) => { gradient[index] += error * value; });
  }
  weights = weights.map((weight, index) => weight - 0.08 * ((gradient[index] / train.length) + (index ? 0.01 * weight : 0)));
}
const score = (row) => sigmoid(normalise(row).reduce((sum, value, index) => sum + value * weights[index], 0));
const predictions = test.map((row) => ({ user_id: row.id, actual_retained_d30: row.y, retention_probability: score(row) }));
const accuracy = predictions.filter((row) => Number(row.retention_probability >= 0.5) === row.actual_retained_d30).length / predictions.length;
const positives = predictions.filter((row) => row.actual_retained_d30 === 1);
const negatives = predictions.filter((row) => row.actual_retained_d30 === 0);
const auc = positives.length && negatives.length ? positives.reduce((sum, positive) => sum + negatives.reduce((inner, negative) => inner + (positive.retention_probability > negative.retention_probability ? 1 : positive.retention_probability === negative.retention_probability ? 0.5 : 0), 0), 0) / (positives.length * negatives.length) : null;
const drivers = featureNames.map((feature, index) => ({ feature, standardized_coefficient: weights[index + 1], direction: weights[index + 1] >= 0 ? "protective" : "risk" })).sort((a, b) => Math.abs(b.standardized_coefficient) - Math.abs(a.standardized_coefficient));
fs.mkdirSync(path.join(root, "reports"), { recursive: true });
fs.writeFileSync(path.join(root, "reports", "retention-model.json"), JSON.stringify({
  model: "Logistic regression (prototype)", train_users: train.length, holdout_users: test.length,
  holdout_accuracy: Number(accuracy.toFixed(3)), holdout_auc: auc === null ? null : Number(auc.toFixed(3)), predictions, drivers,
}, null, 2) + "\n");
fs.writeFileSync(path.join(root, "reports", "retention-driver-ranking.csv"), ["rank,feature,standardized_coefficient,direction", ...drivers.map((driver, index) => `${index + 1},${driver.feature},${driver.standardized_coefficient.toFixed(4)},${driver.direction}`)].join("\n") + "\n");
const report = ["# Prototype retention model", "", "Generated by `npm run model:train`.", "", `- Model: logistic regression`, `- Training users: ${train.length}`, `- Holdout users: ${test.length}`, `- Holdout accuracy: ${(accuracy * 100).toFixed(1)}%`, `- Holdout AUC: ${auc === null ? "not calculable" : auc.toFixed(3)}`, "", "## Driver ranking", "", "| Rank | Feature | Direction | Standardized coefficient |", "| ---: | --- | --- | ---: |", ...drivers.map((driver, index) => `| ${index + 1} | ${driver.feature} | ${driver.direction} | ${driver.standardized_coefficient.toFixed(4)} |`), "", "## Limitation", "", "This is a pipeline demonstration using 12 synthetic records. The holdout metrics are not valid evidence of production model quality and must not be compared with the PRD AUC target.", ""].join("\n");
fs.writeFileSync(path.join(root, "reports", "retention-model-report.md"), report);
console.log(`Trained prototype model; holdout accuracy ${(accuracy * 100).toFixed(1)}%, AUC ${auc === null ? "n/a" : auc.toFixed(3)}.`);
